### ISSUE TITLE
Consider `import` of generated PO files rather than use of `part` statements

### ISSUE THREAD

**Issue by chalin** [google/pageloader#145]
For both site-www and site-webdev, we'd like to continue running the analyzer on example sources _before_ attempting to build a package. We can't do that anymore with the current pageloader scheme since missing `part` files are reported as errors (unless we also commit generated files, which I prefer not doing).

As was mentioned in #132, use of `import` allows us to benefit from the analyzer's ability to ignore `uri_has_not_been_generated` issues. Could we switch to using `import`, or at least have that option, for pageloader?

(I've created this separate issue because #132 is covering a different, though related, issue.)

cc @kevmoo @mk13 @natebosch @kwalrath

**Comment by matanlurey** [comment]
I think this is an orthogonal issue. Angualr doesn't use `import` because it's better, we are using it because it is a NP-hard task to transition to `part` files at this point. Had we started again over, we probably would also use part files.

The analyzer team is close to adding support for the build system, so everything should be found.

**Comment by kevmoo** [comment]
And if you're creating a web app, you're liking running build all the time
(even via serve)
