### ISSUE TITLE
Change event on text inputs is triggered when typing, should happen on blur.

### ISSUE THREAD

**Issue by mihaibogdan10** [google/pageloader#197]
Link to code where this happens: https://github.com/google/pageloader/blob/b7b5eb1a991e9fc9747ff98f13232c233a6b6eba/lib/src/html/html_page_loader_element.dart#L408

IRL, this event is only triggered on blur for inputs of type text & textareas ([mozilla docs link](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/change_event)):

> When the element loses focus after its value was changed, but not commited (e.g., after editing the value of \<textarea> or \<input type="text">).

**Comment by mk13** [comment]
I'll mark this as a `bug` for now, but I need to investigate this a bit further. This will cause several breakages internally since `change` event has been sent regardless of `blur` since PageLoader2. I'll have to assess the impact of this change and make some changes first to stabilize these breakages.

**Comment by mk13** [comment]
Making this change vs. clean-up required isn't worth it.

`HtmlPageLoaderElement` is not meant to be a 100% mirror of real user & browser interaction. Instead it focuses on "testable" events. For example, **uncommitted** text within some input is rarely useful alone for testing and the `input`/`change` events are more useful.

Rather than having the user add verbose code to mimic every human interaction, many of the API calls on `HtmlPageLoaderElement` have implicit behaviors to make testing easier to write.

In addition, you may call the following to mimic the behavior of text value change without the `input`/`change` event:

```dart
import 'dart:html'; // for Element class
import 'package:pageloader/html.dart'; // for HtmlPageLoaderElement class

PageLoaderElement someElement = ...; // Assuming this is HtmlPageLoaderElement
final ele = (someElement as HtmlPageLoaderElement).context as Element;
if (ele is InputElementBase) {
  element.value = "blah blah blah";
}
```

If you need fine-grain control of human-like behavior & browser interaction, use `WebdriverPageLoaderElement` which is intended to be slower, but in exchange more accurate in mimicing actual user & browser interactions.
