### ISSUE TITLE
ElementPageLoader always returns null for "name" attribute

### ISSUE THREAD

**Issue by mgreenland** [google/pageloader#73]
If I have an element like:

``` html
<div name="some descriptive name">
```

and then try to access its "name" attribute:

``` dart
var name = await element.attributes['name'];
```

I get back `null` instead of the actual name.

It looks like the library does [correctly grab the value out of the attribute here](https://github.com/google/pageloader/blob/master/dart/async/lib/html.dart#L447), but then [clobbers it with `null` later on](https://github.com/google/pageloader/blob/master/dart/async/lib/html.dart#L487).

It looks like the actual element [has a `name` field](https://cloud.githubusercontent.com/assets/602239/14397425/27bb1162-fd92-11e5-8b30-d7d0b672f651.png), even though it doesn't show up when drilling down into the thing with devtools.

**Comment by DrMarcII** [comment]
The current behavior was implemented to reflect the WebDriver spec for getAttribute at the time this code was written.

Interestingly, the spec has changed since then, splitting properties from attributes. Presumably the current implementations of WebDriver aren't implementing the new spec yet, but maybe we should change to PageLoader to correctly implement it. This would not that be difficult (would need to to use JS for the WebDriverPageLoader case).

**Comment by DrMarcII** [comment]
I have split attributes from properties, and `await element.attributes['name'];` should work correctly now.
